import edpLogo from '../assets/edp-logo.png';
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { createUserWithEmailAndPassword, sendPasswordResetEmail, updateProfile, signInWithEmailAndPassword } from 'firebase/auth';
import { doc, serverTimestamp, setDoc } from 'firebase/firestore';
import { auth, db } from '../firebase';
import { audit } from '../auth';

export function Login(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const navigate=useNavigate();const submit=async e=>{e.preventDefault();setError('');try{await signInWithEmailAndPassword(auth,email,password);navigate('/dashboard')}catch(err){setError(err.message)}};return <AuthCard title="EDP Records"><p className="muted">Sign in to your account</p><form onSubmit={submit}><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><button>Login</button>{error&&<p className="error">{error}</p>}</form><div className="auth-links"><Link to="/forgot-password">Forgot password?</Link><span>·</span></div></AuthCard>}
export function ForgotPassword(){const [email,setEmail]=useState('');const [message,setMessage]=useState('');const [error,setError]=useState('');const submit=async e=>{e.preventDefault();setError('');setMessage('');try{await sendPasswordResetEmail(auth,email);setMessage('Password reset email sent. Check your inbox.')}catch(err){setError(err.message)}};return <AuthCard title="Reset password"><p className="muted">Enter your email and Firebase will send a reset link.</p><form onSubmit={submit}><input placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><button>Send reset link</button>{message&&<p className="success">{message}</p>}{error&&<p className="error">{error}</p>}</form><p><Link to="/login">Back to login</Link></p></AuthCard>}
function AuthCard({title,children}){return <div className="auth-page"><div className="content-card auth-card"><div className="brand-lockup auth-brand"><img className="brand-logo-img auth-logo-img" src={edpLogo} alt="EDP logo" /><span><strong>EDP Records</strong><small>STOCK LEDGER &amp; TRACKING</small></span></div><h1>{title}</h1>{children}</div></div>}
